-- CMS Foundation Migration
-- Execute per client instance in Supabase SQL editor.

-- 1) Feature flags per instance
alter table public.site_settings
add column if not exists enabled_modules jsonb default '{
  "dashboard": true,
  "blog": true,
  "portfolio": true,
  "microsaas": true,
  "media": true,
  "settings": true
}'::jsonb;

-- 2) Audit logs
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid,
  action text not null,
  entity text not null,
  entity_id text,
  payload jsonb default '{}'::jsonb
);

create index if not exists idx_audit_logs_created_at on public.audit_logs (created_at desc);
create index if not exists idx_audit_logs_actor on public.audit_logs (actor_id);

alter table public.audit_logs enable row level security;

drop policy if exists "audit_logs_admin_read" on public.audit_logs;
create policy "audit_logs_admin_read"
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid() and ur.role = 'admin'
  )
);

drop policy if exists "audit_logs_admin_write" on public.audit_logs;
create policy "audit_logs_admin_write"
on public.audit_logs
for insert
to authenticated
with check (
  exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid() and ur.role = 'admin'
  )
);

-- 3) Frontend app errors
create table if not exists public.app_errors (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid,
  page text,
  message text not null,
  stack text,
  metadata jsonb default '{}'::jsonb
);

create index if not exists idx_app_errors_created_at on public.app_errors (created_at desc);

alter table public.app_errors enable row level security;

drop policy if exists "app_errors_insert_authenticated" on public.app_errors;
create policy "app_errors_insert_authenticated"
on public.app_errors
for insert
to authenticated
with check (auth.uid() = user_id or user_id is null);

drop policy if exists "app_errors_admin_read" on public.app_errors;
create policy "app_errors_admin_read"
on public.app_errors
for select
to authenticated
using (
  exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid() and ur.role = 'admin'
  )
);
